# Generated by Django 4.2.2 on 2023-07-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=200)),
                ("precio", models.IntegerField()),
                ("fecha_de_registro", models.DateField()),
                (
                    "estatus",
                    models.CharField(
                        choices=[("DISP", "Disponible"), ("AGOT", "Agotado")],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
