# Generated by Django 4.2.2 on 2023-06-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Sin titulo", max_length=300, verbose_name="Titulo"
                    ),
                ),
                (
                    "edicion",
                    models.CharField(
                        default="Sin edicion", max_length=300, verbose_name="Titulo"
                    ),
                ),
                (
                    "editorial",
                    models.CharField(
                        default="Sin editorial", max_length=300, verbose_name="Titulo"
                    ),
                ),
                (
                    "año_de_publicacion",
                    models.CharField(
                        default="Sin año de publicación",
                        max_length=300,
                        verbose_name="Titulo",
                    ),
                ),
                ("pagina", models.IntegerField(default=0, verbose_name="Pagina")),
            ],
        ),
    ]
